const translations = {
  id: {
    title: "Warung Makan Kuncoro",
    home:  "Beranda",
    products: "Produk",
    contact: "Kontak",
    hero1: "Dari dapur kami",
    hero2: "ke meja Anda",
    hero3: "dengan cinta",
    homeContent: "Produk Terlaris",
    filterAll: "Semua Kategori",
    filterFood: "Makanan",
    filterDrink: "Minuman",
    filterSearch: "Cari produk...",
    contactUs: "Hubungi Kami",
    name: "Nama",
    email: "Email",
    message: "Pesan",
    submit: "Kirim",
    addToCart: "Tambah ke Keranjang",
    cart: "Keranjang",
    cartInfo: "Keranjang Anda kosong",
    buttonRemove: "Hapus",
    buttonCheckout: "Proses Pesanan",
    footer: "© 2023 Warung Makan Kuncoro. Semua hak dilindungi undang-undang.",
    productsTable: "Tabel Produk",
 
  },
  en: {
    title: "Kuncoro Food Stall",
    home: "Home",
    products: "Products",
    contact: "Contact",
    homeContent: "Best Seller Products",
    hero1: "From our kitchen",
    hero2: "to your table",
    hero3: "with love",
    filterAll: "All Categories",
    filterFood: "Food",
    filterDrink: "Drinks",
    filterSearch: "Search products...",
    contactUs: "Contact Us",
    name: "Name",
    email: "Email",
    message: "Message",
    submit: "Submit",
    addToCart: "Add to Cart",
    cart: "Cart",
    cartInfo: "Your cart is empty",
    buttonRemove: "Remove",
    buttonCheckout: "Proceed to Checkout",
    footer: "© 2023 Kuncoro Food Stall. All rights reserved.",
    productsTable: "Products Table",
  },
};

export default translations;
